const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST'
const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
const GET_FILMS_ERROR = 'GET_FILMS_ERROR'

const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR'

const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST'
const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR'
const NEW_SEARCH_REQUEST = 'NEW_SEARCH_REQUEST'
const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY'
export {
	GET_FILMS_REQUEST,
	GET_FILMS_SUCCESS,
	GET_FILMS_ERROR,
	//
	GET_MOVIE_REQUEST,
	GET_MOVIE_SUCCESS,
	GET_MOVIE_ERROR,
	//
	GET_SEARCH_REQUEST,
	GET_SEARCH_SUCCESS,
	GET_SEARCH_ERROR,
	CHANGE_SEARCH_QUERY,
	NEW_SEARCH_REQUEST,
}
