const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST'
const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
const GET_FILMS_ERROR = 'GET_FILMS_ERROR'

const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR'

export {
	GET_FILMS_REQUEST,
	GET_FILMS_SUCCESS,
	GET_FILMS_ERROR,
	GET_MOVIE_REQUEST,
	GET_MOVIE_SUCCESS,
	GET_MOVIE_ERROR,
}
