const GET_BEST_REQUEST = 'GET_BEST_REQUEST'
const GET_BEST_SUCCESS = 'GET_BEST_SUCCESS'
const GET_BEST_ERROR = 'GET_BEST_ERROR'
const NEW_BEST_REQUEST = 'NEW_BEST_REQUEST'
const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR'
const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST'
const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR'
const NEW_SEARCH_REQUEST = 'NEW_SEARCH_REQUEST'
const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY'
const GET_FAV_FILM_REQUEST = 'GET_FAV_FILM_REQUEST'
const GET_FAV_FILM_SUCCESS = 'GET_FAV_FILM_SUCCESS'
const GET_FAV_FILM_ERROR = 'GET_FAV_FILM_ERROR'
const ADD_FAV_ID = 'ADD_FAV_ID'
const DEL_FAV_ID = 'DEL_FAV_ID'
const CLEAR_FAVS = 'CLEAR_FAVS'
const ADD_GENRE_ID = 'ADD_GENRE_ID'
const DEL_GENRE_ID = 'DEL_GENRE_ID'
const CHANGE_SORT = 'CHANGE_SORT'
const CHANGE_SORT_DIRECTION = 'CHANGE_SORT_DIRECTION'

const QUERY = 'query'
const FILTER = 'filter'

const POPULARITY = 'popularity'
const RELEASE_DATE = 'release_date'
const REVENUE = 'revenue'
const VOTE_AVERAGE = 'vote_average'
const VOTE_COUNT = 'vote_count'
const ASC = 'asc'
const DESC = 'desc'
const API_KEY = '9d923168206684ddbd944abae426483e'
export {
	//actions
	//bests
	GET_BEST_REQUEST,
	GET_BEST_SUCCESS,
	GET_BEST_ERROR,
	NEW_BEST_REQUEST,
	//specific film
	GET_MOVIE_REQUEST,
	GET_MOVIE_SUCCESS,
	GET_MOVIE_ERROR,
	//search by query
	GET_SEARCH_REQUEST,
	GET_SEARCH_SUCCESS,
	GET_SEARCH_ERROR,
	NEW_SEARCH_REQUEST,
	//favorites
	GET_FAV_FILM_REQUEST,
	GET_FAV_FILM_SUCCESS,
	GET_FAV_FILM_ERROR,
	ADD_FAV_ID,
	DEL_FAV_ID,
	CLEAR_FAVS,
	//filters
	ADD_GENRE_ID,
	DEL_GENRE_ID,
	CHANGE_SORT,
	CHANGE_SORT_DIRECTION,
	CHANGE_SEARCH_QUERY,
	//modes
	QUERY,
	FILTER,
	//types of sort
	POPULARITY,
	RELEASE_DATE,
	REVENUE,
	VOTE_AVERAGE,
	VOTE_COUNT,
	//directions of sort
	ASC,
	DESC,
	//api key
	API_KEY,
}
